package cucumber.perf.api.formatter;


import java.util.HashMap;
import java.util.List;

import cucumber.perf.api.result.statistics.Stats;

/**
 * Interface for plugins that create statistics.
 */
public interface StatisticCreator extends Minion {
	
    /**
     * Run the minion plugin
     * @param sortedResults the sortedResults to use in statistic creation.
     * @return Stats the statistics generated by this plugin.
     */
    Stats run(HashMap<String,List<Long>> sortedResults);

}